# Generated by Django 6.0.6 on 2026-06-11 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField(unique=True)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activities_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('misc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_destination_id', models.UUIDField(blank=True, null=True)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='itineraries.itinerary')),
            ],
            options={
                'db_table': 'itinerary_days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=1)),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('activity', 'Activity'), ('hotel', 'Hotel'), ('transport', 'Transport')], max_length=50)),
                ('transport_mode', models.CharField(blank=True, choices=[('car', 'Car'), ('bus', 'Bus'), ('walk', 'Walk'), ('bike', 'Bike')], max_length=30, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itineraries.itineraryday')),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['order_index'],
                'unique_together': {('day', 'title')},
            },
        ),
    ]
