# Generated by Django 6.0.6 on 2026-06-18 07:35

import itineraries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryday',
            name='date',
            field=models.DateField(validators=[itineraries.models.validate_future_date]),
        ),
    ]
