# Generated by Django 6.0.6 on 2026-06-11 06:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptResponseLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('prompt_text', models.TextField()),
                ('response_text', models.TextField()),
                ('model', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField()),
                ('response_tokens', models.IntegerField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_prompt_response_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_usage_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
