# Generated by Django 6.0.6 on 2026-06-11 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aipromptresponselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
