# Generated by Django 6.0.6 on 2026-06-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='travel_interests',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
