# Generated by Django 5.2.4 on 2026-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='travel_interests',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
