# Generated by Django 6.0.6 on 2026-06-21 11:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, validators=[accounts.models.validate_future_datetime]),
        ),
    ]
