# Generated by Django 6.0.6 on 2026-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='selected_interests',
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='food_preferences',
            field=models.CharField(blank=True, choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='preferred_transport_modes',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('train', 'Train'), ('car', 'Car'), ('plane', 'Plane')], max_length=20, null=True),
        ),
    ]
