# Generated by Django 6.0.6 on 2026-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_socialaccount_token_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='selected_interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.interest'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('culture', 'Culture'), ('nature', 'Nature'), ('food', 'Food'), ('sports', 'Sports'), ('tech', 'Technology'), ('music', 'Music'), ('mountains', 'Mountains'), ('historical_places', 'Historical Places'), ('food_tourism', 'Food Tourism'), ('wildlife', 'Wildlife'), ('museums', 'Museums'), ('adventure_sports', 'Adventure Sports'), ('religious_tourism', 'Religious Tourism'), ('photography', 'Photography'), ('shopping', 'Shopping'), ('luxury_travel', 'Luxury Travel'), ('camping', 'Camping'), ('road_trips', 'Road Trips')], max_length=20, unique=True),
        ),
    ]
