# Generated by Django 6.0.6 on 2026-06-11 06:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('best_visiting_season', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_budget_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_budget_mid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avg_budget_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('popular_categories', models.JSONField(blank=True, default=list, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('accommodation_type', models.CharField(choices=[('budget', 'Budget'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=10)),
                ('avg_price_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='destination.destination')),
            ],
            options={
                'ordering': ['destination__city_name', 'accommodation_type', 'hotel_name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Local', 'Local Cuisine'), ('Fast Food', 'Fast Food'), ('Fine Dining', 'Fine Dining'), ('Street Food', 'Street Food'), ('Cafe', 'Cafe')], max_length=50)),
                ('cuisine_type', models.CharField(blank=True, choices=[('Pakistani', 'Pakistani'), ('Chinese', 'Chinese'), ('Continental', 'Continental'), ('Fast Food', 'Fast Food'), ('BBQ', 'BBQ'), ('Sea Food', 'Sea Food')], max_length=50, null=True)),
                ('avg_cost_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='destination.destination')),
            ],
            options={
                'ordering': ['destination__city_name', '-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private', 'Private Vehicle'), ('taxi', 'Taxi/Ride-hailing'), ('metro', 'Metro/Public Transport'), ('mixed', 'Mixed')], max_length=30)),
                ('provider', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_options', to='destination.destination')),
            ],
            options={
                'ordering': ['destination__city_name', 'transport_type', 'estimated_cost'],
            },
        ),
        migrations.CreateModel(
            name='CostBenchmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('travel_style', models.CharField(choices=[('budget', 'Budget'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=20)),
                ('avg_hotel_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_food_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_transport_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_activity_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_price_per_litre', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_benchmarks', to='destination.destination')),
            ],
            options={
                'unique_together': {('destination', 'travel_style')},
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Museum', 'Museum'), ('Park', 'Park'), ('Historical', 'Historical'), ('Religious', 'Religious'), ('Adventure', 'Adventure'), ('Shopping', 'Shopping')], max_length=50)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destination.destination')),
            ],
            options={
                'ordering': ['destination__city_name', 'name'],
                'unique_together': {('destination', 'name')},
            },
        ),
    ]
