# Generated by Django 5.2.15 on 2026-06-18 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='costbenchmark',
            name='avg_activity_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='costbenchmark',
            name='avg_food_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='costbenchmark',
            name='avg_hotel_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='costbenchmark',
            name='avg_transport_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='costbenchmark',
            name='fuel_price_per_litre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_budget_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_budget_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='avg_budget_mid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='hotelrecommendation',
            name='avg_price_high',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='hotelrecommendation',
            name='avg_price_low',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='hotelrecommendation',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='avg_cost_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='transportrecommendation',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='attraction',
            constraint=models.CheckConstraint(condition=models.Q(('entry_fee__gte', 0)), name='attraction_entry_fee_positive'),
        ),
        migrations.AddConstraint(
            model_name='attraction',
            constraint=models.CheckConstraint(condition=models.Q(('duration_hours__gte', 0), ('duration_hours__isnull', True), _connector='OR'), name='attraction_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='costbenchmark',
            constraint=models.CheckConstraint(condition=models.Q(('avg_hotel_per_night__gte', 0)), name='benchmark_hotel_positive'),
        ),
        migrations.AddConstraint(
            model_name='costbenchmark',
            constraint=models.CheckConstraint(condition=models.Q(('avg_food_per_day__gte', 0)), name='benchmark_food_positive'),
        ),
        migrations.AddConstraint(
            model_name='costbenchmark',
            constraint=models.CheckConstraint(condition=models.Q(('avg_transport_per_day__gte', 0)), name='benchmark_transport_positive'),
        ),
        migrations.AddConstraint(
            model_name='costbenchmark',
            constraint=models.CheckConstraint(condition=models.Q(('avg_activity_per_day__gte', 0)), name='benchmark_activity_positive'),
        ),
        migrations.AddConstraint(
            model_name='costbenchmark',
            constraint=models.CheckConstraint(condition=models.Q(('fuel_price_per_litre__gte', 0), ('fuel_price_per_litre__isnull', True), _connector='OR'), name='benchmark_fuel_positive'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('avg_budget_low__gte', 0), ('avg_budget_low__isnull', True), _connector='OR'), name='avg_budget_low_positive'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('avg_budget_mid__gte', 0), ('avg_budget_mid__isnull', True), _connector='OR'), name='avg_budget_mid_positive'),
        ),
        migrations.AddConstraint(
            model_name='destination',
            constraint=models.CheckConstraint(condition=models.Q(('avg_budget_high__gte', 0), ('avg_budget_high__isnull', True), _connector='OR'), name='avg_budget_high_positive'),
        ),
        migrations.AddConstraint(
            model_name='hotelrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('avg_price_low__gte', 0)), name='hotel_price_low_positive'),
        ),
        migrations.AddConstraint(
            model_name='hotelrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('avg_price_high__gte', 0)), name='hotel_price_high_positive'),
        ),
        migrations.AddConstraint(
            model_name='hotelrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 0), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='hotel_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('avg_cost_per_person__gte', 0)), name='restaurant_cost_positive'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 0), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='restaurant_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='transportrecommendation',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost__gte', 0)), name='transport_cost_positive'),
        ),
    ]
