# Generated by Django 5.2.15 on 2026-06-17 23:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('traveller_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('travel_style', models.CharField(choices=[('budget', 'Budget'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=10)),
                ('transport_preference', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private', 'Private Vehicle'), ('taxi', 'Taxi/Ride-hailing'), ('metro', 'Metro/Public Transport'), ('mixed', 'Mixed')], default='mixed', max_length=30)),
                ('itinerary_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('shared', 'Shared'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('max_days', models.IntegerField(default=0, editable=False)),
                ('max_destinations', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('traveller_count__gte', 1)), name='traveller_count_positive'), models.CheckConstraint(condition=models.Q(('budget_total__gt', 0)), name='budget_total_positive'), models.CheckConstraint(condition=models.Q(('max_destinations__gte', 1)), name='max_destinations_positive')],
            },
        ),
        migrations.CreateModel(
            name='SharedTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('who_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_trips', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_link', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_type', models.CharField(choices=[('total', 'Total Budget'), ('per_person', 'Per Person')], default='total', max_length=10)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('mobility_requirements', models.TextField(blank=True, null=True)),
                ('preferred_transport_modes', models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private', 'Private Vehicle'), ('taxi', 'Taxi/Ride-hailing'), ('metro', 'Metro/Public Transport'), ('mixed', 'Mixed')], default='mixed', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='SharedTripUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_users', to='trip.sharedtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_trips_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['shared_trip', 'user'], name='trip_shared_shared__10d488_idx')],
                'unique_together': {('shared_trip', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trip.trip')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_between_1_and_5')],
                'unique_together': {('user', 'trip')},
            },
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('nights', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_destinations', to='destination.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destinations', to='trip.trip')),
            ],
            options={
                'ordering': ['order_index'],
                'constraints': [models.CheckConstraint(condition=models.Q(('order_index__gte', 1)), name='order_index_positive'), models.CheckConstraint(condition=models.Q(('nights__gte', 0)), name='nights_positive'), models.CheckConstraint(condition=models.Q(('route_distance_km__gte', 0)), name='route_distance_positive')],
                'unique_together': {('trip', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='TripInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='destination.interest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='trip.trip')),
            ],
            options={
                'unique_together': {('trip', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='trip.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_trips',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'trip')},
            },
        ),
    ]
