# Generated by Django 6.0.6 on 2026-06-11 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('traveller_count', models.IntegerField()),
                ('budget_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('travel_style', models.CharField(choices=[('budget', 'Budget'), ('comfort', 'Comfort'), ('luxury', 'Luxury')], max_length=10)),
                ('transport_preference', models.CharField(choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private', 'Private Vehicle'), ('taxi', 'Taxi/Ride-hailing'), ('metro', 'Metro/Public Transport'), ('mixed', 'Mixed')], default='mixed', max_length=30)),
                ('itinerary_json', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('shared', 'Shared'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('max_days', models.IntegerField(default=14)),
                ('max_destinations', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('who_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_trips', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_link', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimated_total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accommodation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activities_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fuel_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('misc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('nights', models.IntegerField(default=0)),
                ('route_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_destinations', to='destination.destination')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_destinations', to='trip.trip')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('trip', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=255, null=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trip.itinerary')),
                ('trip_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='trip.tripdestination')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='TripPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_type', models.CharField(choices=[('total', 'Total Budget'), ('per_person', 'Per Person')], default='total', max_length=10)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('mobility_requirements', models.TextField(blank=True, null=True)),
                ('preferred_transport_modes', models.JSONField(blank=True, default=list, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(default=1)),
                ('time', models.TimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('food', 'Food & Dining'), ('activity', 'Activity'), ('hotel', 'Hotel/Accommodation'), ('transport', 'Transport')], max_length=50)),
                ('transport_mode', models.CharField(blank=True, choices=[('flight', 'Flight'), ('train', 'Train'), ('bus', 'Bus'), ('private', 'Private Vehicle'), ('taxi', 'Taxi/Ride-hailing'), ('metro', 'Metro/Public Transport'), ('mixed', 'Mixed')], max_length=30, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tips', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip.itineraryday')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('day', 'title')},
            },
        ),
        migrations.CreateModel(
            name='SharedTripUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_with_users', to='trip.sharedtrip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_trips_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['shared_trip', 'user'], name='trip_shared_shared__10d488_idx')],
                'unique_together': {('shared_trip', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TripInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='destination.interest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='trip.trip')),
            ],
            options={
                'unique_together': {('trip', 'interest')},
            },
        ),
    ]
